version: "3"

services:
  eldritch-builder:
    container_name: eldritch-builder
    image: node:latest
    build:
      context: .
      dockerfile: ./.docker/dockerfiles/node-builder.dev.dockerfile
    volumes:
      - ./:/var/app/:rw
    command: /var/scripts/node-builder.sh

  eldritch-nginx:
    container_name: eldritch-nginx
    image: nginx
    build:
      context: .
      dockerfile: ./.docker/dockerfiles/nginx.dockerfile
    networks:
      - eldritch-network
    ports:
      - "80:80"
    volumes:
      - ./:/var/app/:ro

networks:
  eldritch-network:
    driver: bridge
