#!/bin/bash

docker-compose stop
docker-compose rm
docker system prune -f

# Stop all containers
docker stop $(docker ps -a -q)

# Delete all containers
docker rm $(docker ps -a -q)

# Delete all images
docker rmi $(docker images -q)
